InventoryManagementSystem/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using InventoryManagementSystem.Data;

namespace InventoryManagementSystem.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;
        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            ViewBag.msg = "";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(string userrole)
        {
            string msg = "";
            if (!string.IsNullOrEmpty(userrole))
            {
                if (await roleManager.RoleExistsAsync(userrole))
                {
                    msg = "Role [" + userrole + "] already exists !!!";
                }
                else
                {
                    IdentityRole r = new IdentityRole(userrole);
                    await roleManager.CreateAsync(r);
                    msg = "Role [" + userrole + "] has been created successfully !!!";
                }

            }
            else
            {
                msg = "Please enter a valid role name !!!";
            }
            ViewBag.msg = msg;
            return View("Index");
        }
        public IActionResult AssignRole()
        {
            ViewBag.users = userManager.Users;
            ViewBag.roles = roleManager.Roles;
            ViewBag.msg = TempData["msg"];
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AssignRole(string userdata, string roledata)
        {
            string msg = "";
            if (!string.IsNullOrEmpty(userdata) && !string.IsNullOrEmpty(roledata))
            {
                ApplicationUser u = await userManager.FindByEmailAsync(userdata);
                if (u != null)
                {
                    if (await roleManager.RoleExistsAsync(roledata))
                    {
                        if (await userManager.IsInRoleAsync(u, roledata))
                        {
                            msg = "Role [" + roledata + "] already assigned to " + userdata + " !!!";
                        }
                        else
                        {
                            await userManager.AddToRoleAsync(u, roledata);
                            msg = "Role [" + roledata + "] has been assigned to " + userdata + " successfully !!!";
                        }
                    }
                    else
                    {
                        await userManager.GetUsersInRoleAsync(roledata);
                        msg = "Role [" + roledata + "] doesn't exists !!!";
                    }
                }
                else
                {
                    msg = userdata + "Not Found !!!";
                }

            }
            else
            {
                msg = "Please select a valid user and role";
            }
            ViewBag.users = userManager.Users;
            ViewBag.roles = roleManager.Roles;
            ViewBag.msg = msg;
            return View("AssignRole");
        }
    }
}

InventoryManagementSystem/Views/Role/AssignRole.cshtml
@{
    ViewData["Title"] = "AssignRole";
}


<h1 class="alert alert-info">Assign Role to Users</h1>
<div class="row">
    <h2 class="text-primary text-center">@ViewBag.msg</h2>
</div>
<div class="row">
    <div class="col-6 m-auto">
        <form asp-action="AssignRole" asp-controller="Role" method="post">
            <label class="col-form-label">User</label>
            <select name="userdata" class="form-control">
                <option value="">---Select User----</option>
                @foreach (var item in ViewBag.users)
                {
                    <option class="@item.Email">@item.Email</option>
                }
            </select>

            <label class="col-form-label">Role</label>
            <select name="roledata" class="form-control">
                <option value="">---Select Role----</option>
                @foreach (var item in ViewBag.roles)
                {
                    <option class="@item.NormalizedName">@item.NormalizedName</option>
                }
            </select>

            <button type="submit" class="btn btn-primary btn-sm">Assign Role</button>
        </form>
    </div>
</div>

InventoryManagementSystem/Views/Role/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1 class="alert alert-info">Role Management</h1>
<div class="row">
    <h2 class="text-primary text-center">@ViewBag.msg</h2>
</div>
<div class="row">
    <div class="col-6">
        <form asp-action="CreateRole" asp-controller="Role" method="post">
            <label class="col-form-label">Role Name</label>
            <input type="text" name="userrole" value="" class="form-control" placeholder="Please type role name" />
            <button type="submit" class="btn btn-primary btn-sm">Create Roll</button>
        </form>
    </div>
</div>