InventoryManagementSystem/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InventoryManagementSystem.Models;

namespace InventoryManagementSystem.Controllers
{
    public class CategoriesController : Controller
    {
        private SellManagementDBContext db;
        public CategoriesController(SellManagementDBContext db) 
        {
            this.db = db;
        }
        // GET: Categories

        public ActionResult Index()
        {
            ViewBag.products = db.Products.ToList();
            return PartialView(db.Categories.OrderByDescending(x => x.CategoryId).ToList());
        }
        public ActionResult Create()
        {
            return PartialView(new Category());
        }
        [HttpPost]
        public ActionResult Create(Category c)
        {
            if (ModelState.IsValid && (c.CategoryName != null))
            {
                db.Categories.Add(c);
                db.SaveChanges();
                return Ok("success");
            }
            return Ok("failed");
        }
        public ActionResult Edit(int id)
        {
            return PartialView(db.Categories.First(x => x.CategoryId == id));
        }
        [HttpPost]
        public ActionResult Edit(Category c)
        {
            if (ModelState.IsValid && (c.CategoryName != null))
            {
                db.Entry(c).State = EntityState.Modified;
                db.SaveChanges();
                return Ok("success");
            }
            return Ok("failed");
        }
        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                Category c = new Category() { CategoryId = (int)id };
                db.Entry(c).State = EntityState.Deleted;
                db.SaveChanges();
                return PartialView("_success");
            }
            return PartialView("_error");
        }
    }
}

InventoryManagementSystem/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InventoryManagementSystem.Models;

namespace InventoryManagementSystem.Controllers
{
    public class CustomersController : Controller
    {
        private readonly SellManagementDBContext db;

        public CustomersController(SellManagementDBContext db)
        {
            this.db = db;
        }

        public ActionResult Index()
        {
            ViewBag.orders = db.Orders.ToList();
            return PartialView(db.Customers.OrderByDescending(x => x.CustomerId).ToList());
        }
        public ActionResult Create()
        {
            return PartialView(new Customer());
        }
        [HttpPost]
        public ActionResult Create(Customer c)
        {
            if (ModelState.IsValid && (c.CustomerName != null && c.CustomerAddress != null))
            {
                db.Customers.Add(c);
                db.SaveChanges();
                return Ok("success");
            }
            return Ok("failed");
        }
        public ActionResult Edit(int id)
        {
            return PartialView(db.Customers.First(x => x.CustomerId == id));
        }
        [HttpPost]
        public ActionResult Edit(Customer c)
        {
            if (ModelState.IsValid)
            {
                db.Entry(c).State = EntityState.Modified;
                db.SaveChanges();
                return Ok("success");
            }
            return Ok("failed");
        }
        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                Customer c = new Customer() { CustomerId = (int)id };
                db.Entry(c).State = EntityState.Deleted;
                db.SaveChanges();
                return Ok("success");
            }
            return Ok("failed");
        }
    }
}

InventoryManagementSystem/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InventoryManagementSystem.Models;
using InventoryManagementSystem.ViewModels;

namespace InventoryManagementSystem.Controllers
{
    public class OrdersController : Controller
    {
        private readonly SellManagementDBContext db;

        public OrdersController(SellManagementDBContext db)
        {
            this.db = db;
        }
        public ActionResult Index()
        {
            return PartialView(db.Orders.OrderByDescending(x => x.OrderId).Include(x => x.Customer).Include(x => x.OrderDetails).ThenInclude(x => x.Product).ToList());
        }
        public ActionResult Create()
        {
            ViewBag.customers = new SelectList(db.Customers, "CustomerId", "CustomerName");
            ViewBag.products = new SelectList(db.Products, "ProductId", "ProductName");

            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(Order order, int[] singleProductId, int[] SingleProductQuantity)
        {
            ModelState.Remove("Customer.CustomerName");
            ModelState.Remove("Customer.CustomerAddress");
            if (ModelState.IsValid)
            {
                if (order.Customer.CustomerId != 0)
                {
                    Order or = new Order()
                    {
                        CustomerId = order.Customer.CustomerId

                    };

                    if (singleProductId != null && singleProductId.Count() > 0)
                    {
                        for (int i = 0; i < singleProductId.Length; i++)
                        {
                            if (singleProductId[i] == 0)
                                continue;

                            OrderDetail od = new OrderDetail()
                            {
                                Order = or,
                                OrderId = or.OrderId,
                                ProductId = singleProductId[i],
                                Price = db.Products.Find(singleProductId[i]).Price,
                                Quantity = SingleProductQuantity[i]
                            };
                            db.OrderDetails.Add(od);
                        }
                    }
                    db.SaveChanges();
                    return Ok("success");
                }
            }
            ViewBag.customers = new SelectList(db.Customers, "CustomerId", "CustomerName");
            ViewBag.products = new SelectList(db.Products, "ProductId", "ProductName");
            return Ok("failed");
        }
        public ActionResult Edit(int id)
        {
            //Order currentOrder = db.Orders.First(x => x.OrderId == id);

            Order currentOrder = db.Orders.Where(x => x.OrderId == id).Include(x => x.Customer).Single();
            var orderDetailsList = db.OrderDetails.Where(x => x.OrderId == currentOrder.OrderId);

            ViewBag.customers = new SelectList(db.Customers, "CustomerId", "CustomerName");
            ViewBag.products = db.Products.ToList();

            OrderVM orderVM = new OrderVM() { Order = currentOrder };

            foreach (var item in orderDetailsList)
            {
                orderVM.OrderDetails.Add(new OrderDetailVM()
                {
                    OrderDetailsId = item.OrderDetailId,
                    OrderId = item.OrderId,
                    ProductId = item.ProductId,
                    Quantity = item.Quantity,
                    Price = item.Price
                });
            }

            return PartialView(orderVM);
        }

        [HttpPost]
        public ActionResult Edit(OrderVM orderVM, int[] ProductId, int[] Quantity)
        {
            if (orderVM.OrderDetails != null || (ProductId != null && ProductId.Length > 0))
            {

                if (orderVM.OrderDetails.Count() > 0)
                {
                    foreach (var item in orderVM.OrderDetails)
                    {
                        OrderDetail postedOrder = new OrderDetail()
                        {
                            OrderDetailId = item.OrderDetailsId,
                            OrderId = orderVM.Order.OrderId,
                            ProductId = item.ProductId,
                            Quantity = item.Quantity,
                            Price = db.Products.Find(item.ProductId).Price
                        };

                        if (item.Delete == true)
                        {
                            db.Entry(postedOrder).State = EntityState.Deleted;
                            continue;
                        }

                        db.Entry(postedOrder).State = EntityState.Modified;
                    }
                    db.SaveChanges();
                }


                //Add newly added items
                if (ProductId != null && ProductId.Length > 0)
                {
                    for (int i = 0; i < ProductId.Length; i++)
                    {
                        if (ProductId[i] == 0)
                        {
                            continue;
                        }
                        OrderDetail orderDetail = new OrderDetail()
                        {
                            OrderId = orderVM.Order.OrderId,
                            ProductId = ProductId[i],
                            Quantity = Quantity[i],
                            Price = db.Products.Find(ProductId[i]).Price,
                        };

                        db.OrderDetails.Add(orderDetail); ;
                    }
                    db.SaveChanges();
                }
                return Ok("success");
            }

            return Ok("failed");
        }
        public ActionResult Delete(int id)
        {
            Order order = db.Orders.Find(id);
            if (order != null)
            {
                var orderDetail = db.OrderDetails.Where(x => x.OrderId == id).ToList();
                if (orderDetail.Count == 0)
                {
                    db.Entry(order).State = EntityState.Deleted;
                    db.SaveChanges();
                    return PartialView("_success");
                }
                if ((orderDetail != null) && (orderDetail.Count() > 0))
                {
                    foreach (var item in orderDetail)
                    {
                        db.Entry(item).State = EntityState.Deleted;
                    }
                    db.SaveChanges();

                    db.Entry(order).State = EntityState.Deleted;
                    db.SaveChanges();
                    return Ok("success");
                }
                return Ok("failed");
            }
            return Ok("failed");
        }
        public ActionResult SingleProductEntry()
        {
            ViewBag.products = new SelectList(db.Products, "ProductId", "ProductName");
            return PartialView();
        }
        public ActionResult SingleProductEditEntry()
        {
            ViewBag.customers = new SelectList(db.Customers, "CustomerId", "CustomerName");
            ViewBag.products = new SelectList(db.Products, "ProductId", "ProductName");

            return PartialView(new OrderDetail());
        }
        public JsonResult GetFee(int id)
        {
            var t = db.Products.FirstOrDefault(x => x.ProductId == id);
            return Json(t == null ? 0 : t.Price);
        }
    }
}

InventoryManagementSystem/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InventoryManagementSystem.Models;
using InventoryManagementSystem.ViewModels;
using static NuGet.Packaging.PackagingConstants;

namespace InventoryManagementSystem.Controllers
{
    public class ProductsController : Controller
    {
        private readonly SellManagementDBContext db;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductsController(SellManagementDBContext db, IWebHostEnvironment hostEnvironment)
        {
            this.db = db;
            _hostEnvironment = hostEnvironment;
        }

        public ActionResult Index()
        {
            ViewBag.orderDetails = db.OrderDetails.ToList();
            return PartialView(db.Products.OrderByDescending(x => x.ProductId).Include(x => x.Category).ToList());
        }
        public ActionResult Create()
        {
            ViewBag.categories = new SelectList(db.Categories, "CategoryId", "CategoryName");
            return PartialView(new ProductVM());
        }
        [HttpPost]
        public ActionResult Create(ProductVM pvm)
        {
            if (ModelState.IsValid)
            {
                Product pr = new Product()
                {
                    ProductName = pvm.ProductName,
                    CategoryId = pvm.CategoryId,
                    Price = pvm.Price,
                    Quantity = pvm.Quantity,
                    SKUCode = pvm.SKUCode,
                    EntryDate = pvm.EntryDate,
                    InStock = pvm.InStock
                };

                if (pvm.Picture != null)
                {
                    string webroot = _hostEnvironment.WebRootPath;
                    string folder = "Images";
                    string filePath = Guid.NewGuid().ToString() + Path.GetExtension(Path.GetFileName(pvm.Picture.FileName));
                    string fileToSave = Path.Combine(webroot, folder, filePath);

                    using (var stream = new FileStream(fileToSave, FileMode.Create))
                    {
                        pvm.Picture.CopyTo(stream);
                        pr.PicturePath = "/" + folder + "/" + filePath;
                    }
                }
                else
                {
                    pr.PicturePath = "/" + "Images" + "/" + "default.jpg";
                }

                db.Products.Add(pr);
                db.SaveChanges();
                return Ok("success");
            }
            return Ok("failed");

        }
        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                Product? pr = db.Products.Find(id);

                ProductVM pvm = new ProductVM()
                {
                    ProductId = pr.ProductId,
                    ProductName = pr.ProductName,
                    CategoryId = pr.CategoryId,
                    Price = pr.Price,
                    Quantity = pr.Quantity,
                    SKUCode = pr.SKUCode,
                    EntryDate = pr.EntryDate,
                    PicturePath = pr.PicturePath,
                    InStock = pr.InStock
                };

                ViewBag.categories = new SelectList(db.Categories, "CategoryId", "CategoryName");
                return PartialView(pvm);
            }
            return View();
        }
        [HttpPost]
        public ActionResult Edit(ProductVM productVM)
        {
            if (ModelState.IsValid)
            {
                Product pr = new Product()
                {
                    ProductId = productVM.ProductId,
                    ProductName = productVM.ProductName,
                    CategoryId = productVM.CategoryId,
                    Price = productVM.Price,
                    Quantity = productVM.Quantity,
                    SKUCode = productVM.SKUCode,
                    EntryDate = productVM.EntryDate,
                    PicturePath = productVM.PicturePath,
                    InStock = productVM.InStock
                };

                if (productVM.Picture != null)
                {
                    string webroot = _hostEnvironment.WebRootPath;
                    string folder = "Images";
                    string filePath = Guid.NewGuid().ToString() + Path.GetExtension(Path.GetFileName(productVM.Picture.FileName));
                    string fileToSave = Path.Combine(webroot, folder, filePath);

                    using (var stream = new FileStream(fileToSave, FileMode.Create))
                    {
                        productVM.Picture.CopyToAsync(stream);
                        pr.PicturePath = "/" + folder + "/" + filePath;
                    }
                }

                db.Entry(pr).State = EntityState.Modified;
                db.SaveChanges();
                return Ok("success");
            }
            return Ok("failed");
        }

        public ActionResult Delete(int id)
        {
            var pr = db.Products.Find(id);
            if (pr != null)
            {
                db.Entry(pr).State = EntityState.Deleted;
                db.SaveChanges();
                return Ok("success");
            }
            return Ok("failed");
        }
    }
}

InventoryManagementSystem/Views/Home/Index.cshtml
@model InventoryManagementSystem.ViewModels.DataVM
@{
    ViewData["Title"] = "Home Page";
}

<div class="d-flex justify-content-between border p-2 mb-3 pe-0" style="box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px">
    <div class="col-md-6 pe-2" id="CustomerViewSection" style="overflow-y: auto; height:210px">
        @{
            await Html.RenderPartialAsync("~/Views/Customers/index.cshtml", Model.Customers);
        }
    </div>

    <div class="col-md-6 ps-2 pe-2" id="CategoryViewSection" style="overflow-y: auto; height:210px">
        @{
            await Html.RenderPartialAsync("~/Views/Categories/index.cshtml", Model.Categories);
        }
    </div>
</div>

<div id="ProductViewSection" class="border p-2 mb-3" style="height: 216px; overflow: hidden; overflow-y: scroll; box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px">
    @{
        await Html.RenderPartialAsync("~/Views/Products/index.cshtml", Model.Products);
    }
</div>

<div id="OrderViewSection" class="border p-2 mb-4" style="box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px">
    @{
        await Html.RenderPartialAsync("~/Views/Orders/index.cshtml", Model.Orders);
    }
</div>

@*Modal for Insert, Update, Delete*@

<div class="modal fade" id="CustomModal">
    <div class="modal-dialog modal-lg" style="width:900px !important;">
        <div class="modal-content">
            <div class="modal-header d-flex justify-content-between">
                <h4 class="text-muted" id="ModalHeading"></h4>
                <button id="BtnModalClose" class="btn btn-warning" type="button">&times;</button>
            </div>
            <div class="modal-body">
                <div id="ModalDataSection">
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script>
        $(document).ready(function () {
            //RefreshPage();
        });

        //All Ajax call
        function loadData(hrefData, state) {
            if (state === "delete") {
                if (!window.confirm("Are you sure you want to delete this item?")) {
                    return;
                }
            }

            $.ajax(
                {
                    type: 'GET',
                    url: hrefData
                }
            ).done((data) => {
                switch (state) {
                    case "add":
                        $("#ModalDataSection").html(data);
                        $("#CustomModal").modal("show");
                        break;
                    case "addSingleProduct":
                        $("#ModalDataSection").html(data);
                        $("#CustomModal").modal("show");
                        break;
                    case "edit":
                        $("#ModalDataSection").html(data);
                        $("#CustomModal").modal("show");
                        break;
                    case "delete":
                        RefreshPage();
                        floatingMessage.Show('Success', 'Deleteted Successful !!!');
                        break;

                    case "CategoryRefresh":
                        $("#CategoryViewSection").html(data);
                        break;
                    case "CustomerRefresh":
                        $("#CustomerViewSection").html(data);
                        break;
                    case "ProductRefresh":
                        $("#ProductViewSection").html(data);
                        break;
                    case "OrderRefresh":
                        $("#OrderViewSection").html(data);
                        break;

                    default:
                        break;
                }
            }

            ).fail(() => {
                floatingMessage.Show('Error', 'An error occured !!!');
            });
        }


        //Load Partial Page 

        $(document).on('click', 'a[data-type="loadpage"]', function (e) {

            e.preventDefault();
            e.stopImmediatePropagation();

            var hrefData = $(this).attr("href");

            switch ($(this).attr('id')) {
                //Add Category Page
                case 'BtnAddNewCategory':
                    loadData(hrefData, "add");
                    break;
                //Edit Category Page
                case 'BtnEditCategory':
                    loadData(hrefData, "edit");
                    break;
                //Delete Category
                case 'BtnDeleteCategory':
                    loadData(hrefData, "delete");
                    break;
                //Add Customer Page
                case 'BtnAddNewCustomer':
                    loadData(hrefData, "add");
                    break;
                //Edit Customer Page
                case 'BtnEditCustomer':
                    loadData(hrefData, "edit");
                    break;
                //Delete Customer
                case 'BtnDeleteCustomer':
                    loadData(hrefData, "delete");
                    break;
                //Add Product Page
                case 'BtnAddNewProduct':
                    loadData(hrefData, "add");
                    break;
                //Edit Product Page
                case 'BtnEditProduct':
                    loadData(hrefData, "edit");
                    break;
                //Delete Product
                case 'BtnDeleteProduct':
                    loadData(hrefData, "delete");
                    break;
                //Add Order Page
                case 'BtnAddNewOrder':
                    loadData(hrefData, "add");
                    break;
                //Edit Order Page
                case 'BtnEditProduct':
                    loadData(hrefData, "edit");
                    break;
                //Delete Customer
                case 'BtnDeleteOrder':
                    loadData(hrefData, "delete");
                    break;

                default:
                    break;
            }

        });


        //Modal close button event
        $(document).on('click', '#BtnModalClose', function (e) {
            e.preventDefault();
            e.stopImmediatePropagation();
            $("#CustomModal").modal("hide");

        });


        //CRUD Operation(INSERT, UPDATE) button click handler

        $(document).on('click', 'button[type="submit"][data-category="CRUD"]', function (e) {

            if ($(this).closest('form')[0].length) {

                e.preventDefault();
                e.stopImmediatePropagation();

                var form = $(this).closest('form')[0];
                var data = new FormData(form);
                var hrefData = $(this).data('href');

                switch ($(this).attr('id')) {

                    //Add New Category
                    case 'btnCategoryAddFormSubmit':
                        SubmitFormToAction(hrefData, data);
                        break;
                    //Update Category
                    case 'btnCategoryEditFormSubmit':
                        SubmitFormToAction(hrefData, data);
                        break;
                    //Add New Customer
                    case 'btnCustomerAddFormSubmit':
                        SubmitFormToAction(hrefData, data);
                        break;
                    //Update Customer
                    case 'btnCustomerEditFormSubmit':
                        SubmitFormToAction(hrefData, data);
                        break;
                    //Add New Product
                    case 'btnProductCreateFormSubmit':
                        var fileData = $("#ProductAddForm input[name='Picture']")[0].files[0];
                        data.append('file', fileData);
                        SubmitFormToAction(hrefData, data);
                        break;

                    //Update Product
                    case 'btnProductEditFormSubmit':
                        var fileData = $("#ProductEditForm input[name='Picture']")[0].files[0];
                        data.append('file', fileData);
                        SubmitFormToAction(hrefData, data);
                        break;
                    //Add New Order
                    case 'btnOrderCreateFormSubmit':
                        SubmitFormToAction(hrefData, data);
                        break;
                    //Add New Order
                    case 'btnOrderEditFormSubmit':
                        SubmitFormToAction(hrefData, data);
                        break;

                    default:
                        break;
                }
            }
        });

        //Ajax call for submit form
        function SubmitFormToAction(hrefData, data) {
            $.ajax(
                {
                    type: 'POST',
                    url: hrefData,
                    data: data,
                    processData: false,
                    contentType: false,
                    cache: false,
                }
            ).done((result) => {
                modalClose();
                if (result == "success") {
                    floatingMessage.Show('Success', 'Operation successful !!!');
                }
                if (result == "failed") {
                    floatingMessage.Show('Failed', 'Operation Failed !!!');
                }
            }).fail(() => {
                floatingMessage.Show('Error', 'An error occured !!!');
            });
        }


        //Click Plus Button to add new single product (Add new order)
        $(document).on('click', '#AddSingleProduct', function (e) {
            e.preventDefault();
            e.stopImmediatePropagation();

            var lastItem = $("#SingleProductSection").find(".singleProductDropdown").last().val();
            if (lastItem == "") {
                return;
            }

            $.ajax({
                type: "GET",
                url: "/Orders/SingleProductEntry",
                success: r => {
                    $("#SingleProductSection").append(r);
                }
            });

        });

        //Click Plus Button to add new single product (Edit Order)
        $(document).on('click', '#AddSingleEditProduct', function (e) {
            e.preventDefault();
            e.stopImmediatePropagation();

            var lastItem = $("#SingleProductEditItemContainer").find(".singleProductEditDropdown").last().val();
            if (lastItem == "") {
                return;
            }

            $.ajax({
                type: "GET",
                url: "/Orders/SingleProductEditEntry",
                success: r => {
                    $("#SingleProductEditItemContainer").append(r);
                }
            });

        });

        //Page refresh on modal closing
        $(document).on('hide.bs.modal', "#CustomModal", function () {
            RefreshPage();
        });

        //Change dropdown of product list to get the price (Add new order)
        $(document).on("change", ".singleProductDropdown", function () {

            var priceBox = $(this).parent().parent().find(".product-price");

            $.ajax({
                type: "POST",
                url: '/Orders/GetFee/' + $(this).val(),
                dataType: "json",
                success: data => {
                    priceBox.val(data);
                }
            });
        });

        //Change dropdown of product list to get the price (Edit order)
        $(document).on("change", ".singleProductEditDropdown", function () {

            var priceBox = $(this).parent().parent().find(".singleProductEditPrice");

            $.ajax({
                type: "POST",
                url: '/Orders/GetFee/' + $(this).val(),
                dataType: "json",
                success: data => {
                    priceBox.html(parseFloat(data).toFixed(4));
                    console.log(data);
                },
                error: priceBox.html("0.0000")
            });
        });

        $(document).on("click", ".single-product-delete", function (e) {

            e.preventDefault();
            $(this).parent().parent().remove();

        });

        //Set Hidden property delete for removal products of OrderDetails(Edit Mode)
        $(document).on("click", ".single-product-edit-delete", function (e) {
            e.preventDefault();
            var deleteItem = $(this).parent().parent();
            deleteItem.find(".delete-hidden").val("true");
            deleteItem.hide();
        });

        //Refresh all section of Home Page
        function RefreshPage() {
            var hrefData = "@Url.Action("Index", "Categories")";
            loadData(hrefData, "CategoryRefresh");

            var hrefData = "@Url.Action("Index", "Customers")";
            loadData(hrefData, "CustomerRefresh");

            var hrefData = "@Url.Action("Index", "Products")";
            loadData(hrefData, "ProductRefresh");

            var hrefData = "@Url.Action("Index", "Orders")";
            loadData(hrefData, "OrderRefresh");
        }

        //Function to close the Modal
        function modalClose(e) {
            $('#CustomModal').modal('hide');
            setTimeout(function () {
                $("#ModalDataSection").html("");
            }, 500);
        }

    </script>
}